alias rcp="rsync -av --progress -h"
#alias rsync-copy="rsync -av --progress -h"
alias rmv="rsync -av --progress -h --remove-source-files"
#alias rsync-move="rsync -av --progress -h --remove-source-files"
alias rup="rsync -avu --progress -h"
#alias rsync-update="rsync -avu --progress -h"
alias rsync-synchronize="rsync -avu --delete --progress -h"
